table DATA
	lineageTag: 2a3e6a63-6f35-47b5-b01e-2282f82acc7d

	measure Qty1 = SUM( DATA[Qty] )
		formatString: 0
		lineageTag: ee8365d6-0b93-4bf0-adac-82efd2c5f339

	column Name
		dataType: string
		lineageTag: 9da8b53b-1ea6-47dc-b7cc-4fd6f9dfc287
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: 5445b624-5cca-450b-9ef9-b4600cacf0a5
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	partition DATA = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8sxLyUxU0lEyNDBQio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Qty = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}, {"Qty", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

